### ISSUE TITLE
Question.. Resizing based on width

### ISSUE THREAD

**Issue by latwelve** [VodkaBears/Vide#60]
I've tried following your doc's but I'm still struggling with how to get the video to resize to the width of the containing div as it seem's height is the default method.

Please can you point me in the right directions

**Comment by VodkaBears** [comment]
By default it resizes only when a window resizes, because elements don't trigger resize events. So, if the only containing div will be resized without the window, it won't. There are two solutions: call the [`#resize`](https://github.com/VodkaBears/Vide#methods) method manually or use something like: https://github.com/cowboy/jquery-resize.
